### ISSUE TITLE
Support Gnome Extensions

### ISSUE THREAD

**Issue by ieugen** [titonbarua/shadow-cljs-gjs-target#3]
Hi,

I discovered the project and I would like to write a gnome extension using ClojureScript.
I think it would be good to have a target for that since it's in the same area.

What do you think?

If you are open to it, I would like to work (with some directions) on how to implement that.
I wonder if we can use REPL during extension development.

See #2 

Regards,
Eugen

**Comment by titonbarua** [comment]
Hello Eugen,
I think it's a great idea, although I have no knowledge regarding how gnome extensions work. I see that you already submitted a pull request. Is the demo extension functional?

**Comment by ieugen** [comment]
Hi, glad to see you are interested.
The demo is not functional.

The basics:
* metadata.json with extension information
* extension.js with an `init()`, `enable()`, `disable()` , etc. functions that gnome shell will run
* other files (styleshee.css, etc). 
* Have the `imports` global object available (and not mangled during minification)

There is a video tutorial here https://www.youtube.com/playlist?list=PLr3kuDAFECjZhW-p56BoVB7SubdUHBVQT 
With source code here https://gitlab.com/justperfection.channel/how-to-create-a-gnome-shell-extension/ .

For the initial setup, only first 2-3 videos are relevant (~20-30 min)
You might be able to watch it on 1.5x . 
The tutorial is ~ 2-3h of content.


Right now the compilation output (app.js), for my function definitions is quite large considering I have a few empty functions.

**Comment by titonbarua** [comment]
The changes proposed here and implemented in pull request #2 has been merged. Thanks! I am now closing this issue.
